name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        dotnet-version: '3.1'

    - name: Verify msbuild installation
      run: msbuild -version

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build
      run: msbuild LibraryManagement.sln /p:Configuration=Release
