name: Build

on: [push]

jobs:
  build:
    runs-on: windows-2019    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add MSDeploy to PATH
      run: |
        $msdeployPath = "C:\Program Files\IIS\Microsoft Web Deploy V3"  # Update with the correct path to MSDeploy
        echo "##[set-env name=PATH]$msdeployPath;$env:PATH"
    
    - name: Verify PATH command
      run: echo $env:PATH

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        dotnet-version: '6.0.x'    

    - name: Verify msbuild installation
      run: msbuild -version

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build
      run: msbuild LibraryManagement.sln /p:Configuration=Release

    - name: Publish using MSDeploy
      run: |
        $msdeployArgs = "-verb:sync -source:contentPath='bin\Release\publish' -dest:package='$PWD\library\LibraryPackage.zip'"
        |
        msdeploy $msdeployArgs
